ENT.Type 			= "anim"
ENT.Base 			= "base_wire_entity"
ENT.PrintName			= "Balloon Deployer"
ENT.Author			= "LuaPinapple"
ENT.Contact			= "evilpineapple@cox.net"
ENT.Purpose			= "Figure it out man."
ENT.Instructions		= "Use wire."
